### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Salsah#246]
## yarn or npm?

The [README](https://github.com/dhlab-basel/Salsah/blob/develop/README.md) says to use `yarn` instead of `npm`, but the [Sphinx docs](https://dhlab-basel.github.io/Salsah/documentation/guidelines/rst/get-started.html) say to use `npm`.

## yarn install errors

```
$ yarn install --production=false

yarn install v1.6.0
(node:12105) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error lcov-result-merger@2.0.0: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

The README says I need Node 6.9.0 or higher, which I have:

```
$ node --version
v10.0.0
```

## ng serve fails

```
$ ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:195:32)
    at ServeCommand.<anonymous> (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/command-runner.js:87:23)
```

**Comment by benjamingeer** [comment]
Solution:

```
$ brew install node yarn npm
$ npm install -g n
$ sudo n 8.9.0
$ yarn install --production=false
```

**Comment by sofiag** [comment]
Sorry, I can't find the reference I had used anymore, it was in some forum. 

Indeed you should use '''yarn'''.
The error mentions that node version should be '''">=4 <=9"'''
I also had node version 10.0.0. 
I don't know when this error started exactly, but yes, we should mention a fix in the README.

**Comment by kilchenmann** [comment]
Thanks Ben. We have to update the documentation anyway and the readme file.

**Comment by kilchenmann** [comment]
Yes, in the Readme we recommend to use yarn. But normally it doesn't matter if you use yarn or npm. 
I will update Readme and docs with the following solution:

```
$ brew install node yarn
$ yarn global add n
$ n 8.9.0
$ yarn install --production=false
